# Generated by Django 2.0.4 on 2021-12-04 22:08

from django.db import migrations, models
import django.db.models.deletion
import root.models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('percentage_maori', models.FloatField(blank=True, null=True)),
                ('maori_word_count', models.IntegerField(blank=True, null=True)),
                ('ambiguous_word_count', models.IntegerField(blank=True, null=True)),
                ('other_word_count', models.IntegerField(blank=True, null=True)),
                ('total_word_count', models.IntegerField(blank=True, null=True)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrape.Publication')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, root.models.AutoSetterGetterMixin),
        ),
        migrations.RemoveField(
            model_name='page',
            name='publication',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
    ]
