# Generated by Django 2.0.4 on 2021-12-04 22:18

from django.db import migrations, models
import django.db.models.deletion
import root.models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0002_auto_20211204_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.AutoField(auto_created=True, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('percentage_maori', models.FloatField(blank=True, null=True)),
                ('maori_word_count', models.IntegerField(blank=True, null=True)),
                ('ambiguous_word_count', models.IntegerField(blank=True, null=True)),
                ('other_word_count', models.IntegerField(blank=True, null=True)),
                ('total_word_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, root.models.AutoSetterGetterMixin),
        ),
        migrations.RemoveField(
            model_name='article',
            name='ambiguous_word_count',
        ),
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
        migrations.RemoveField(
            model_name='article',
            name='maori_word_count',
        ),
        migrations.RemoveField(
            model_name='article',
            name='other_word_count',
        ),
        migrations.RemoveField(
            model_name='article',
            name='percentage_maori',
        ),
        migrations.RemoveField(
            model_name='article',
            name='total_word_count',
        ),
        migrations.AddField(
            model_name='paragraph',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrape.Article'),
        ),
    ]
