# Generated by Django 2.0.4 on 2021-12-04 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0003_auto_20211204_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='url',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
