# Generated by Django 2.0.4 on 2022-01-07 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0004_article_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paragraph',
            name='index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
